apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        #image: gcr.io/kodekloud-gcp-training/test-gcpdevops:latest
        image: gcr.io/upbeat-polygon-386810/gcpdevops:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "50000"